version: 2
updates:
  - package-ecosystem: "pip"
    # Look for a `Dockerfile` in the `go-demo` directory
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
