name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc #v6.4.3
        with:
          version: "0.8.2"
          python-version: "3.10"
      - name: Bootstrap venv
        run: make init
      - name: Run tests
        run: make lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    name: Run tests (Python ${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc #v6.4.3
        with:
          version: "0.8.2"
          python-version: ${{ matrix.python-version }}
      - name: Bootstrap venv
        run: make init
      - name: Run test suite
        run: uv run tox -e ${{ matrix.python-version }}